"""Binding generation from Custom Elements Manifests (SPEC 13.2).

``virel bind`` reads a custom-elements.json file (the standard manifest
format emitted by web-component tooling) and generates a Python module of
typed ``ui.web_component`` bindings, so third-party elements get prop
validation and documented events without hand-written wrappers.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from .expr import VirelCompileError

_TYPE_MAP = {
    "string": "str",
    "number": "float",
    "boolean": "bool",
}


@dataclass
class ComponentSpec:
    tag: str
    class_name: str
    summary: str
    props: dict[str, str] = field(default_factory=dict)  # name -> python type
    events: list[str] = field(default_factory=list)


def _python_name(tag: str) -> str:
    return "".join(part.capitalize() for part in tag.split("-"))


def _python_type(manifest_type: str | None) -> str:
    if not manifest_type:
        return "str"
    text = manifest_type.strip().lower()
    # Union types like "string | undefined" reduce to their first concrete
    # member; anything unrecognized binds as str.
    for part in text.replace("|", " ").split():
        if part in _TYPE_MAP:
            return _TYPE_MAP[part]
    return "str"


def parse_manifest(data: dict) -> list[ComponentSpec]:
    if "modules" not in data:
        raise VirelCompileError(
            "This file is not a custom elements manifest: missing the "
            "top-level 'modules' list."
        )
    specs: list[ComponentSpec] = []
    for module in data.get("modules", []):
        for declaration in module.get("declarations", []):
            if not declaration.get("customElement"):
                continue
            tag = declaration.get("tagName")
            if not tag or "-" not in tag:
                continue
            spec = ComponentSpec(
                tag=tag,
                class_name=_python_name(tag),
                summary=(declaration.get("summary")
                         or declaration.get("description", "")).strip(),
            )
            for attribute in declaration.get("attributes", []):
                name = attribute.get("name")
                if not name:
                    continue
                type_text = (attribute.get("type") or {}).get("text")
                spec.props[name.replace("-", "_")] = _python_type(type_text)
            for event in declaration.get("events", []):
                name = event.get("name")
                if name:
                    spec.events.append(name)
            specs.append(spec)
    if not specs:
        raise VirelCompileError(
            "The manifest declares no custom elements (entries need "
            "customElement: true and a hyphenated tagName)."
        )
    return specs


def generate_bindings(specs: list[ComponentSpec], module_url: str,
                      source_name: str) -> str:
    lines = [
        f"\"\"\"Typed web-component bindings generated by `virel bind` from",
        f"{source_name}. Regenerate instead of editing.\"\"\"",
        "",
        "from virel import ui",
        "",
    ]
    for spec in specs:
        lines.append("")
        if spec.summary:
            for text in spec.summary.splitlines():
                lines.append(f"# {text}".rstrip())
        if spec.events:
            handlers = ", ".join(
                f"on_{event.replace('-', '_')}" for event in spec.events)
            lines.append(f"# Events: {handlers}")
        lines.append(f"{spec.class_name} = ui.web_component(")
        lines.append(f'    tag="{spec.tag}",')
        lines.append(f'    module="{module_url}",')
        if spec.props:
            lines.append("    props={")
            for name, python_type in spec.props.items():
                lines.append(f'        "{name}": {python_type},')
            lines.append("    },")
        if spec.events:
            events = ", ".join(f'"{event}"' for event in spec.events)
            lines.append(f"    events=[{events}],")
        lines.append(")")
    return "\n".join(lines) + "\n"


def bind_manifest(manifest_path: Path, module_url: str) -> str:
    try:
        data = json.loads(manifest_path.read_text("utf-8"))
    except json.JSONDecodeError as error:
        raise VirelCompileError(
            f"{manifest_path} is not valid JSON: {error}"
        ) from None
    specs = parse_manifest(data)
    return generate_bindings(specs, module_url, manifest_path.name)


# ---------------------------------------------------------------------------
# npm packages (SPEC 13.2): fetch, vendor, and bind in one step
# ---------------------------------------------------------------------------

_REGISTRY_URL = "https://registry.npmjs.org"
_MAX_PACKAGE_BYTES = 64 * 1024 * 1024


def _default_fetcher(url: str) -> bytes:
    import urllib.request
    request = urllib.request.Request(url, headers={
        "User-Agent": "virel-bind"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def bind_npm(package: str, project_root: Path, *,
             version: str = "latest",
             fetcher=None) -> tuple[str, Path]:
    """Fetch a package from the npm registry, vendor its files under
    vendor/<name>, and generate typed bindings from the custom elements
    manifest it publishes. Returns (bindings_source, vendor_dir).

    TypeScript declarations are not parsed; the custom elements
    manifest is the standard packages publish for exactly this, which
    is the "where possible" of SPEC 13.2."""
    import re as _re
    if not _re.fullmatch(r"(@[\w.-]+/)?[\w.-]+", package):
        raise VirelCompileError(f"Invalid npm package name {package!r}.")
    fetch = fetcher or _default_fetcher
    import urllib.parse
    metadata = json.loads(fetch(
        f"{_REGISTRY_URL}/{urllib.parse.quote(package, safe='@')}"))
    if version == "latest":
        version = metadata.get("dist-tags", {}).get("latest")
    release = (metadata.get("versions") or {}).get(version)
    if not release:
        raise VirelCompileError(
            f"npm package {package!r} has no version {version!r}.")
    tarball_url = release.get("dist", {}).get("tarball")
    if not tarball_url or not tarball_url.startswith("https://"):
        raise VirelCompileError(
            f"npm release {package}@{version} has no https tarball.")

    simple_name = package.split("/")[-1]
    vendor_dir = project_root / "vendor" / simple_name
    _extract_package(fetch(tarball_url), vendor_dir)

    package_json = {}
    manifest_path = vendor_dir / "package.json"
    if manifest_path.exists():
        package_json = json.loads(manifest_path.read_text("utf-8"))
    manifest_file = package_json.get("customElements",
                                     "custom-elements.json")
    manifest = vendor_dir / manifest_file
    if not manifest.exists():
        raise VirelCompileError(
            f"{package}@{version} publishes no custom elements manifest "
            f"({manifest_file}); virel bind needs one to generate typed "
            "bindings. Point `virel bind <manifest>` at one if the "
            "package documents its elements elsewhere.")
    specs = parse_manifest(json.loads(manifest.read_text("utf-8")))

    entry = (package_json.get("module") or package_json.get("main")
             or "index.js").lstrip("./")
    mount = f"/vendor/{simple_name}"
    style = package_json.get("style")
    header = [
        f'"""Typed web-component bindings generated by',
        f'`virel bind npm {package}` ({package}@{version}).',
        "Regenerate instead of editing.",
        "",
        "Server rendering emits each tag with its attributes; the element",
        "upgrades in the browser once its module loads. Wrap instances in",
        'ui.Island(load="visible") to defer that load below the fold.',
        '"""',
        "",
        "from pathlib import Path",
        "",
        "from virel import ui",
        "",
        f'_VENDOR = Path(__file__).resolve().parents[1] / "vendor" / '
        f'"{simple_name}"',
        f'ui.use_static("{mount}", _VENDOR)',
    ]
    if style:
        header.append(
            f"ui.use_css('@import url(\"{mount}/{style.lstrip('./')}\");')")
    body = generate_bindings(specs, f"{mount}/{entry}",
                             f"{package}@{version}")
    body = body.split('"""', 2)[2].lstrip("\n")  # replace the header
    return "\n".join(header) + "\n\n" + body, vendor_dir


def _extract_package(tarball: bytes, vendor_dir: Path) -> None:
    """Extract the npm tarball's package/ directory safely: no absolute
    paths, no traversal, no links, bounded total size."""
    import io
    import shutil
    import tarfile
    if vendor_dir.exists():
        shutil.rmtree(vendor_dir)
    vendor_dir.mkdir(parents=True)
    total = 0
    with tarfile.open(fileobj=io.BytesIO(tarball), mode="r:gz") as archive:
        for member in archive:
            if not member.isfile():
                continue
            name = member.name
            if name.startswith(("/", "..")) or ".." in name.split("/"):
                raise VirelCompileError(
                    f"npm tarball entry {name!r} escapes the package "
                    "directory; refusing to extract.")
            parts = name.split("/", 1)
            if len(parts) != 2:  # everything lives under package/
                continue
            relative = parts[1]
            total += member.size
            if total > _MAX_PACKAGE_BYTES:
                raise VirelCompileError(
                    "npm package exceeds the 64 MB extraction limit.")
            target = vendor_dir / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            source = archive.extractfile(member)
            if source is not None:
                target.write_bytes(source.read())
