"""Binding generation from Custom Elements Manifests (SPEC 13.2).

``virel bind`` reads a custom-elements.json file (the standard manifest
format emitted by web-component tooling) and generates a Python module of
typed ``ui.web_component`` bindings, so third-party elements get prop
validation and documented events without hand-written wrappers.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from .expr import VirelCompileError

_TYPE_MAP = {
    "string": "str",
    "number": "float",
    "boolean": "bool",
}


@dataclass
class ComponentSpec:
    tag: str
    class_name: str
    summary: str
    props: dict[str, str] = field(default_factory=dict)  # name -> python type
    events: list[str] = field(default_factory=list)


def _python_name(tag: str) -> str:
    return "".join(part.capitalize() for part in tag.split("-"))


def _python_type(manifest_type: str | None) -> str:
    if not manifest_type:
        return "str"
    text = manifest_type.strip().lower()
    # Union types like "string | undefined" reduce to their first concrete
    # member; anything unrecognized binds as str.
    for part in text.replace("|", " ").split():
        if part in _TYPE_MAP:
            return _TYPE_MAP[part]
    return "str"


def parse_manifest(data: dict) -> list[ComponentSpec]:
    if "modules" not in data:
        raise VirelCompileError(
            "This file is not a custom elements manifest: missing the "
            "top-level 'modules' list."
        )
    specs: list[ComponentSpec] = []
    for module in data.get("modules", []):
        for declaration in module.get("declarations", []):
            if not declaration.get("customElement"):
                continue
            tag = declaration.get("tagName")
            if not tag or "-" not in tag:
                continue
            spec = ComponentSpec(
                tag=tag,
                class_name=_python_name(tag),
                summary=(declaration.get("summary")
                         or declaration.get("description", "")).strip(),
            )
            for attribute in declaration.get("attributes", []):
                name = attribute.get("name")
                if not name:
                    continue
                type_text = (attribute.get("type") or {}).get("text")
                spec.props[name.replace("-", "_")] = _python_type(type_text)
            for event in declaration.get("events", []):
                name = event.get("name")
                if name:
                    spec.events.append(name)
            specs.append(spec)
    if not specs:
        raise VirelCompileError(
            "The manifest declares no custom elements (entries need "
            "customElement: true and a hyphenated tagName)."
        )
    return specs


def generate_bindings(specs: list[ComponentSpec], module_url: str,
                      source_name: str) -> str:
    lines = [
        f"\"\"\"Typed web-component bindings generated by `virel bind` from",
        f"{source_name}. Regenerate instead of editing.\"\"\"",
        "",
        "from virel import ui",
        "",
    ]
    for spec in specs:
        lines.append("")
        if spec.summary:
            for text in spec.summary.splitlines():
                lines.append(f"# {text}".rstrip())
        if spec.events:
            handlers = ", ".join(
                f"on_{event.replace('-', '_')}" for event in spec.events)
            lines.append(f"# Events: {handlers}")
        lines.append(f"{spec.class_name} = ui.web_component(")
        lines.append(f'    tag="{spec.tag}",')
        lines.append(f'    module="{module_url}",')
        if spec.props:
            lines.append("    props={")
            for name, python_type in spec.props.items():
                lines.append(f'        "{name}": {python_type},')
            lines.append("    },")
        lines.append(")")
    return "\n".join(lines) + "\n"


def bind_manifest(manifest_path: Path, module_url: str) -> str:
    try:
        data = json.loads(manifest_path.read_text("utf-8"))
    except json.JSONDecodeError as error:
        raise VirelCompileError(
            f"{manifest_path} is not valid JSON: {error}"
        ) from None
    specs = parse_manifest(data)
    return generate_bindings(specs, module_url, manifest_path.name)
