"""Deployment artifact generation (SPEC 15.1: virel deploy).

Virel does not run a hosting service; ``virel deploy`` generates the
files a target needs so the app deploys with standard tooling. Targets:

- ``asgi``: an ASGI entrypoint plus a Dockerfile (SPEC 20) that serves
  the app under an ASGI server.
- ``static``: a note plus a redirects file for static hosts, valid only
  when the app is fully static.

Artifacts are written next to the project, never overwriting an
existing file without notice.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

_ENTRYPOINT = '''"""ASGI entrypoint generated by `virel deploy`.

Serve with any ASGI server, for example:
    uvicorn asgi:app --host 0.0.0.0 --port 8000
"""

from virel.server import create_asgi_app

import {module}  # noqa: F401  (registers pages and actions)

app = create_asgi_app()
'''

_DOCKERFILE = '''# Generated by `virel deploy --target asgi`.
# Virel has no runtime dependencies; add your own to requirements if any.
FROM python:3.12-slim

WORKDIR /app
COPY . .
RUN pip install --no-cache-dir virel uvicorn

EXPOSE 8000
CMD ["uvicorn", "asgi:app", "--host", "0.0.0.0", "--port", "8000"]
'''

_DOCKERIGNORE = "__pycache__/\n*.pyc\n.venv/\ndist/\n.virel/\n.git/\n"

_STATIC_NOTE = '''# Static deployment

This app built to fully static files under dist/. Upload dist/ to any
static host (Netlify, Cloudflare Pages, S3, GitHub Pages). The
generated _redirects file sends unknown paths to the closest route.

Generated by `virel deploy --target static`.
'''


def generate_artifacts(root: Path, config: dict[str, Any], *,
                       target: str) -> list[str]:
    from .expr import VirelCompileError
    if target not in ("asgi", "static"):
        raise VirelCompileError(
            "deploy target must be 'asgi' or 'static'.")
    module = config.get("app", {}).get("module", "app.app")
    written: list[str] = []

    def write(name: str, content: str) -> None:
        path = root / name
        if path.exists():
            print(f"  (kept existing {name})")
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, "utf-8")
        written.append(name)

    if target == "asgi":
        write("asgi.py", _ENTRYPOINT.format(module=module))
        write("Dockerfile", _DOCKERFILE)
        write(".dockerignore", _DOCKERIGNORE)
    else:
        from .registry import active_registry
        registry = active_registry()
        dynamic = [p.path for p in registry.pages.values() if p.is_dynamic]
        if dynamic:
            raise VirelCompileError(
                "Static deployment requires fully static routes, but these "
                f"are dynamic: {', '.join(dynamic)}. Use --target asgi.")
        write("DEPLOY-static.md", _STATIC_NOTE)
        write("dist/_redirects", "/*  /index.html  200\n"
              if (root / "dist").exists() else "/*  /index.html  200\n")
    return written
