"""Embedding Virel into existing applications (SPEC 13.4).

Four embedding shapes, all compiled by the production pipeline:

- ``ui.render_fragment(fn)`` produces a static HTML fragment plus an
  optional self-contained script, for server-side inclusion in any
  template system.
- ``ui.as_custom_element(fn, tag=...)`` produces a JavaScript module
  defining a standard custom element; any page, framework, or CMS can
  then write ``<virel-counter></virel-counter>``.
- Islands are the in-page form (``ui.Island``), and route-level
  applications mount through ``virel.integrations`` (PathMount, ASGI).

Fragments and elements scope their bindings to their own container, so
several instances coexist on one host page with independent state.
"""

from __future__ import annotations

import json
import re
import uuid
from dataclasses import dataclass
from typing import Any, Callable

from .expr import VirelCompileError


@dataclass(frozen=True)
class Fragment:
    """A compiled fragment. ``html`` is the static markup for server-side
    inclusion (style it by also serving Virel's app.css); ``script`` is
    the optional self-contained interactivity module; ``document`` is a
    standalone page for iframes and previews."""
    html: str
    script: str
    document: str


def _compile(fn: Callable[[], Any], title: str):
    if not callable(fn):
        raise VirelCompileError(
            "Expected a page or component function.")

    def wrapped():
        from .elements import Page
        from .nodes import PageNode
        result = fn()
        if isinstance(result, PageNode):
            return result
        return Page(result, title=title)

    from .compiler import compile_page
    from .registry import Page as PageRecord
    record = PageRecord(path="/__embed__", fn=wrapped, render="auto")
    return compile_page(record, inline_js=True)


def render_fragment(fn: Callable[[], Any], *,
                    title: str = "Fragment") -> Fragment:
    """Compile a page or component into an embeddable fragment:

        fragment = ui.render_fragment(pricing_table)
        # server-side: include fragment.html in any template, plus
        # fragment.script in one <script type="module"> when the
        # fragment is interactive.

    Bindings scope to the fragment's own container, so multiple
    fragments coexist on a host page."""
    compiled = _compile(fn, title)
    marker = f"vf-{uuid.uuid4().hex[:10]}"
    html = (f'<div data-virel-fragment="{marker}">'
            f"{compiled.body_html}</div>")
    script = ""
    if compiled.js:
        from .notebook import _bundle
        bundled = _strip_auto_mount(_bundle(compiled.js))
        script = (
            bundled
            + f'\nconst __root = document.querySelector('
              f'\'[data-virel-fragment="{marker}"]\');\n'
            + "$.setRoot(__root);\ntry { mount(); } finally { "
              "$.setRoot(document); }\n"
        )
    from .notebook import _standalone_document
    return Fragment(html=html, script=script,
                    document=_standalone_document(compiled))


def as_custom_element(fn: Callable[[], Any], *, tag: str) -> str:
    """Compile a page or component into a standard custom element,
    returned as JavaScript module source:

        source = ui.as_custom_element(counter_card, tag="virel-counter")
        Path("public/virel-counter.js").write_text(source)

    Each instance renders into its own shadow root with the compiled
    stylesheet adopted, binds its own state, and disposes cleanly on
    disconnect, so several instances coexist with independent state.
    ``virel element`` is the CLI form."""
    if not re.fullmatch(r"[a-z][a-z0-9]*(-[a-z0-9]+)+", tag):
        raise VirelCompileError(
            f"Custom element tag {tag!r} must be lowercase with a hyphen, "
            "like 'virel-counter'.")
    compiled = _compile(fn, tag)
    from .notebook import _bundle
    from .registry import active_registry
    from .theme import Theme, build_stylesheet
    theme = active_registry().theme or Theme()
    bundled = _strip_auto_mount(_bundle(compiled.js or
                                        "export function mount() {}\n"))
    return (
        f"// {tag}: a Virel component compiled to a standard custom\n"
        "// element. Generated by virel; regenerate instead of editing.\n"
        + bundled
        + f"\nconst TAG = {json.dumps(tag)};\n"
        + f"const BODY = {_js_string(compiled.body_html)};\n"
        + f"const STYLESHEET = {_js_string(build_stylesheet(theme))};\n"
        + """
const sheet = new CSSStyleSheet();
sheet.replaceSync(STYLESHEET);

class VirelElement extends HTMLElement {
  connectedCallback() {
    if (this.__virelMounted) return;
    this.__virelMounted = true;
    const root = this.attachShadow({ mode: "open" });
    root.adoptedStyleSheets = [sheet];
    root.innerHTML = BODY;
    $.setRoot(root);
    try {
      this.__virelDispose = $.captureScope(() => mount());
    } finally {
      $.setRoot(document);
    }
  }

  disconnectedCallback() {
    if (this.__virelDispose) this.__virelDispose();
    this.__virelMounted = false;
  }
}

if (!customElements.get(TAG)) {
  customElements.define(TAG, VirelElement);
}
"""
    )


def _strip_auto_mount(bundle: str) -> str:
    """The page module ends by mounting itself; embedded forms mount per
    instance instead."""
    return re.sub(r"\nmount\(\);\s*$", "\n", bundle)


def _js_string(text: str) -> str:
    """A JS string literal safe to inline anywhere, including inside a
    <script> element."""
    return json.dumps(text).replace("<", "\\u003c").replace(">", "\\u003e")
