"""Typed web-component bindings generated by `virel bind` from
star-rating.manifest.json. Regenerate instead of editing."""

from virel import ui


# Interactive star rating input.
# Events: on_rating_changed
StarRating = ui.web_component(
    tag="star-rating",
    module="/vendor/widgets/star-rating.js",
    props={
        "value": float,
        "max": float,
    },
    events=["rating-changed"],
)
