"""Typed web-component bindings generated by `virel bind` from
widgets.manifest.json. Regenerate instead of editing."""

from virel import ui


# Inline SVG sparkline driven by a comma-separated values attribute.
SparkLine = ui.web_component(
    tag="spark-line",
    module="/public/widgets.js",
    props={
        "values": str,
        "stroke": str,
    },
)

# Self-updating relative timestamp.
RelativeTime = ui.web_component(
    tag="relative-time",
    module="/public/widgets.js",
    props={
        "datetime": str,
    },
)
